export const ADD_REVIEW_MODAL_FORMS = {
    INITIAL: 'INITIAL',
    ADD_VIDEO: 'ADD_VIDEO',
    ADD_MEDIA_TO_PRODUCT_GALLERY: 'ADD_MEDIA_TO_PRODUCT_GALLERY',
    PERSONAL_DATA: 'PERSONAL_DATA',
    SUCCESS_MESSAGE: 'SUCCESS_MESSAGE'
};
