export const ADD_REVIEW_MODAL_ACTIONS = {
    GO_TO_INITIAL_FORM: 'GO_TO_INITIAL_FORM',
    GO_TO_ADD_VIDEO_FORM: 'GO_TO_ADD_VIDEO_FORM',
    GO_TO_ADD_MEDIA_TO_PRODUCT_GALLERY_FORM:
        'GO_TO_ADD_MEDIA_TO_PRODUCT_GALLERY_FORM',
    GO_TO_PERSONAL_DATA_FORM: 'GO_TO_PERSONAL_DATA_FORM',
    GO_TO_SUCCESS_MESSAGE: 'GO_TO_SUCCESS_MESSAGE',
    SET_RATING: 'SET_RATING',
    SET_MEDIA_ITEM_TO_ADD: 'SET_MEDIA_ITEM_TO_ADD',
    RESET_MEDIA_ITEM_TO_ADD: 'RESET_MEDIA_ITEM_TO_ADD',
    SAVE_BASE_FORM_VALUES: 'UPDATE_SAVED_BASE_FORM_VALUES',
    SET_CAT_ITEM_ID: 'SET_CAT_ITEM_ID',
    SET_IS_ADDING_IMAGE: 'SET_IS_ADDING_IMAGE',
    SET_REVIEW_MEDIA: 'SET_REVIEW_MEDIA',
    SET_REVIEW_MEDIA_THUMBNAILS: 'SET_REVIEW_MEDIA_THUMBNAILS',
    REMOVE_MEDIA_ITEM: 'REMOVE_MEDIA_ITEM',
    SET_STAGED_REVIEW_TOKEN: 'SET_STAGED_REVIEW_TOKEN'
};
