export const CREATE_ACCOUNT_ACTIONS = {
    GO_TO_INITIAL_SCREEN: 'GO_TO_INITIAL_SCREEN',
    GO_TO_THAT_IS_ME_SCREEN: 'GO_TO_THAT_IS_ME_SCREEN',
    GO_TO_REG_FORM_SCREEN: 'GO_TO_REG_FORM_SCREEN'
};
