export const APP_ROUTER_PATHS = {
    home: '/',
    signIn: '/sign-in',
    createAccount: '/create-account',
    forgotPassword: '/forgot-password',
    accountPage: '/account',
    accountInformation: '/account-information',
    addressBook: '/address-book',
    addressPage: '/address-book/customer-address/:id',
    addAddressPage: '/address-book/create-customer-address',
    rewardsPage: '/rewards',
    orderHistory: '/order-history',
    orderViewPage: '/order-history/:orderNumber',
    guestOrderViewPage: '/guest/order-history/:orderNumber',
    orderCurbsidePickupPage: '/order-history/:orderNumber/pickup',
    guestOrderCurbsidePickupPage: '/guest/order-history/:orderNumber/pickup',
    faqPage: '/faq',
    storeLocatorPage: '/stores',
    storeDetailsPage: '/stores/:id',
    checkout: '/checkout',
    savedPaymentsPage: '/saved-payments',
    checkoutSuccessPage: '/checkout/success',
    termsAndConditions: '/terms-and-conditions',
    privacyPolicy: '/privacy-policy',
    cart: '/cart'
};
